var found = true;
var grade = 88.6;
var firstName = 'Tam';
var lastName = 'Nguyen';
found = 0;
grade = "A";
firstName = false;
console.log(found);
console.log("the grade is " + grade);
console.log("hi " + firstName + " " + lastName);
